package com.it.sso.dao;

import com.it.sso.pojo.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {



    int deleteByPrimaryKey(Integer id);

    int insert(User record);


    int insertSelective(User record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 31 17:50:59 CST 2020
     */
    User selectByPrimaryKey(Integer id);

         /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 31 17:50:59 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 31 17:50:59 CST 2020
     */
    int updateByPrimaryKey(User record);

    User queryUser(@Param("name") String name);
}